---
- name: stop postfix 
  service: name=postfix state=stopped enabled=no
  
- name: stop rpc.statd 
  service: name=nfslock state=stopped enabled=no
  ignore_errors: yes
  
- name: mayby this service can start rpc.statd
  service: name=portmap state=stopped enabled=no
  ignore_errors: yes