---
- name: install zabbix on centos 6
  yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-agent-3.2.2-1.el6.x86_64.rpm state=present
  when: ansible_distribution_major_version == "6"
  
- name: install zabbix on centos 6
  yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-get-3.2.2-1.el7.x86_64.rpm state=present
  when: ansible_distribution_major_version == "7"
  
- name: touch zabbix agented dirs
  file: path=/usr/local/zabbix_agent/conf/zabbix_agentd state=directory mode=0755
  
- name: copy config files
  copy: src="{{ item.src }}" dest="{{ item.dest }}" 
  with_items:
    - {'src': 'zabbix/zabbix_agentd.conf', 'dest': '/etc/zabbix/'}
    - {'src': 'zabbix/check_io.py',        'dest': '/etc/zabbix/zabbix_agentd.d/'}
    
  notify:
    - restart zabbix 
