---
- hosts: all
  vars:
    hostname: test-01-20
    ip: 192.168.15.20
    ssh_port: 8690
  roles:
    - {'role': 'sys', tags: ['sys-init']}
    - {'role': 'base', tags: ['base']}
    - {'role': 'app', tags: ['service']}
    - {'role': 'user', tags: ['user']}
    - {'role': 'services', tags: ['nginx']}
