---
- name: restart sshd
  service: name=sshd state=restarted

- name: restart network
  service: name=network state=restarted

- name: restart zabbix
  service: name=zabbix-agent state=restarted enabled=True
